[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MatrixTensorFactor = "b7339fc4-c5a0-4c8f-934d-9fd05475ae37"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
